version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    container_name: sqlserver
    ports:
      - "3667:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=tuContraseñaSegura1234$
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_api
    ports:
      - "7663:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AcademiaDB=Server=sqlserver,1433;Database=AcademiaDB;User Id=sa;Password=tuContraseñaSegura1234$;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  sqlserver_data: